export const hobbies = [
'Watercolor Painting',
'Calligraphy or Hand Lettering',
'Digital Photography',
'Pottery',
'Knitting or Crochet',
'Bouldering',
'Geocaching',
'Yoga',
'Social Dancing',
'Hiking',
'Genealogy',
'Chess',
'Learning a New Language',
'Creative Writing',
'Programming',
'Sourdough Baking',
'Fermentation',
'Mixology',
'Coffee Brewing',
'Cake Decorating',
'Urban Gardening',
'Astronomy',
'Bird Watching',
'Aquascaping',
'Woodworking',
'Upcycling',
'3D Printing',
'Candle Making',
'Origami']